name: junk.test
on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]
  workflow_dispatch: {}
jobs:
  test:
    if: |
      github.event_name == 'push' || (
        (
          (github.event_name == 'issue_comment' && github.event.issue.pull_request) ||
          (github.event_name == 'pull_request_review_comment')
        ) &&
        contains(github.event.comment.body, '/test') &&
        !contains(github.event.comment.body, '/test skip')
      )
    runs-on: ubuntu-latest
    permissions:
      statuses: write
    steps:
      - uses: actions/github-script@v7
        id: check
        with:
          result-encoding: string
          debug: true
          script: |
            console.log(context.sha);

            const check = await github.rest.checks.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              head_sha: context.sha,
              status: "in_progress",
              name: context.workflow,
              detail_url: "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}",
            });
      - run: echo test

      - uses: actions/github-script@v7
        if: ${{ failure() }}
        with:
          script: |
            await github.rest.checks.update({
              check_run_id: ${{ steps.check.result }}
              owner: context.repo.owner,
              repo: context.repo.repo,
              status: "completed",
              conclusion: "failure",
            });
      - uses: actions/github-script@v7
        if: ${{ success() }}
        with:
          script: |
            await github.rest.checks.update({
              check_run_id: ${{ steps.check.result }}
              owner: context.repo.owner,
              repo: context.repo.repo,
              sha: context.sha,
              status: "completed",
              conclusion: "success",
            });
      - uses: actions/github-script@v7
        if: ${{ !success() && !failure() }}
        with:
          script: |
            await github.rest.checks.update({
              check_run_id: ${{ steps.check.result }}
              owner: context.repo.owner,
              repo: context.repo.repo,
              sha: context.sha,
              status: "completed",
              conclusion: "neutral",
            });
